#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-orm_adapter
Version  : 0.5.0
Release  : 5
URL      : https://rubygems.org/downloads/orm_adapter-0.5.0.gem
Source0  : https://rubygems.org/downloads/orm_adapter-0.5.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activerecord
BuildRequires : rubygem-bson_ext
BuildRequires : rubygem-bundler
BuildRequires : rubygem-dm-active_model
BuildRequires : rubygem-dm-sqlite-adapter
BuildRequires : rubygem-git
BuildRequires : rubygem-mongoid
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-yard

%description
= ORM Adapter {<img src="https://secure.travis-ci.org/ianwhite/orm_adapter.png?branch=master" alt="Build Status" />}[http://travis-ci.org/ianwhite/orm_adapter]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n orm_adapter-0.5.0
gem spec %{SOURCE0} -l --ruby > rubygem-orm_adapter.gemspec

%build
gem build rubygem-orm_adapter.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
orm_adapter-0.5.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/orm_adapter-0.5.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/.rspec
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/History.txt
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/gemfiles/activerecord-4.gemfile
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/data_mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/mongo_mapper.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/mongoid.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/to_adapter.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/lib/orm_adapter/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/orm_adapter.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/active_record_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/data_mapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/mongo_mapper_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/mongoid_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter/example_app_shared.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/orm_adapter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/orm_adapter-0.5.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/orm_adapter-0.5.0.gemspec
