#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-orm_adapter
Version  : 0.5.0
Release  : 2
URL      : https://rubygems.org/downloads/orm_adapter-0.5.0.gem
Source0  : https://rubygems.org/downloads/orm_adapter-0.5.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-activerecord
BuildRequires : rubygem-bson_ext
BuildRequires : rubygem-bundler
BuildRequires : rubygem-dm-active_model
BuildRequires : rubygem-dm-sqlite-adapter
BuildRequires : rubygem-git
BuildRequires : rubygem-mongoid
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec
BuildRequires : rubygem-rspec-core
BuildRequires : rubygem-sqlite3
BuildRequires : rubygem-yard

%description
= ORM Adapter {<img src="https://secure.travis-ci.org/ianwhite/orm_adapter.png?branch=master" alt="Build Status" />}[http://travis-ci.org/ianwhite/orm_adapter]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n orm_adapter-0.5.0
gem spec %{SOURCE0} -l --ruby > rubygem-orm_adapter.gemspec

%build
gem build rubygem-orm_adapter.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
orm_adapter-0.5.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/orm_adapter-0.5.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Model/cdesc-Model.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/cdesc-OrmAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/create%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/find_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/get%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/OrmAdapter/order_clause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/Resource/cdesc-Resource.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/DataMapper/cdesc-DataMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/cdesc-OrmAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/conditions_to_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/create%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/find_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/get%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/OrmAdapter/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/MongoMapper/cdesc-MongoMapper.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/ClassMethods/cdesc-ClassMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/cdesc-OrmAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/conditions_to_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/create%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/find_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/get%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/OrmAdapter/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/Document/cdesc-Document.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Mongoid/cdesc-Mongoid.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/cdesc-ActiveRecord.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/conditions_to_fields-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/construct_relation-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/create%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/find_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/get%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ActiveRecord/order_clause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/column_names-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/create%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/destroy-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/extract_conditions%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/find_all-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/find_first-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/get%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/get-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/inherited-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/klass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/normalize_order-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/valid_object%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/Base/wrap_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/NotSupportedError/cdesc-NotSupportedError.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/NotSupportedError/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ToAdapter/cdesc-ToAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/ToAdapter/to_adapter-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/adapters-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/OrmAdapter/cdesc-OrmAdapter.ri
/usr/lib64/ruby/gems/2.2.0/doc/orm_adapter-0.5.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/.rspec
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/History.txt
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/gemfiles/activerecord-4.gemfile
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/active_record.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/data_mapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/mongo_mapper.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/adapters/mongoid.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/to_adapter.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/lib/orm_adapter/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/orm_adapter.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/active_record_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/data_mapper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/mongo_mapper_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/adapters/mongoid_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter/example_app_shared.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/orm_adapter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/orm_adapter-0.5.0/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/specifications/orm_adapter-0.5.0.gemspec
